name: Deploy to Webserver
on: 
  push:
      branches:
        - main
jobs:

 
  update-main:
    name: Update Main
    runs-on: ubuntu-latest
    steps:
    - name: Update the Websever Source Code
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: /root/update.sh

