# This is a basic workflow to help you get started with Actions

name: Hash paper_wallet.html

# Controls when the workflow will run
on:
  release:
    tags:
      - "*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  hash:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Command from website
      - name: Generate Release Hashes
        uses: MCJack123/ghaction-Generate-Release-Hashes@v2


      # Sample Form Website
      - uses: MCJack123/ghaction-generate-release-hashes@v1
        with:
          hash-type: md5
          file-name: paper_wallet.html
          
      - uses: actions/upload-artifact@v2
        with:
          name: md5 Hashes
          path: hashes.txt
          
      - name: Build
        id: build
        run: |
          sha256=$(shasum -a 256 "hashes.txt" | awk '{print toupper($1)}')
          release_name=security-hashes
        
      - name: Create Release
        uses: softprops/action-gh-release@v0.1.12
        with:
          files: hashes.txt
          name: md5 Security Hashes
          body: |
            [md5 Security Hashes](hashes.txt) **${{ steps.build.outputs.release_name }}**
            `SHA256 : ${{ steps.hash.outputs.sha256 }}`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
