# This is a basic workflow to help you get started with Actions

name: md5 hash of paper wallet code for security 

# Controls when the workflow will run
on:
  release:
    types: [published]

 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  hash-website:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

     
      - name: Build
        id: build
        run: |
          md5sum paper_wallet.html 2>&1 >> paper_wallet.html.md5
          md5=$(md5sum paper_wallet.html)
          ccx_version=$(echo "$GITHUB_REF" | sed 's|refs/tags/||')
          release_name=bmorecoin-website-v"$ccx_version"
          echo "::set-output name=ccx_version::${ccx_version}"
          echo "::set-output name=md5::${md5}"

      - name: Create Release
        uses: softprops/action-gh-release@v0.1.12
        with:
          files: paper_wallet.html.md5
          name: BMoreCoin Website ${{ steps.build.outputs.ccx_version }}
          body: |
            ${{ steps.build.outputs.md5 }
     
            
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
