# This is a basic workflow to help you get started with Actions

name: Hash html website files for security 

# Controls when the workflow will run
on:
  release:
    types: [published]

 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  hash:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

     
      - name: Build
        id: build
        run: |
          md5sum *.html 2>&1 >> hashes.html
          ccx_version=$(echo "$GITHUB_REF" | sed 's|refs/tags/||')
          release_name=bmorecoin-website-v"$ccx_version"
     
          

        
      - name: Create Release
        uses: softprops/action-gh-release@v0.1.12
        with:
          files: hashes.html
          name: BMoreCoin Website ${{ steps.build.outputs.ccx_version }}
          body: |
            [md5 Security Hashes](../../releases/download/${{ steps.build.outputs.ccx_version }}/hashes.html)
            
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
