name: Deploy to Webserver
on: 
  push:
      branches:
        - main
jobs:
 
  release-hashes:
    name: Generate Release Hashes
    runs-on: ubuntu-latest
    steps:
    - uses: MCJack123/ghaction-generate-release-hashes@v1
      with:
        hash-type: sha1
        file-name: hashes.txt
    - uses: actions/upload-artifact@v2
      with:
        name: Asset Hashes
        path: hashes.txt
