- name: Generate Release Hashes
  uses: MCJack123/ghaction-Generate-Release-Hashes@v2
on: 
  push:
      branches:
        - main
jobs:

  hash:
  - uses: MCJack123/ghaction-generate-release-hashes@v2
  with:
    hash-type: md5
    file-name: hashes.txt
- uses: actions/upload-artifact@v2
  with:
    name: Asset Hashes
    path: hashes.txt
